signing_key: "skibidi"
debug: false

orchestrator: {}

agent:
  orchestrator_host: orchestrator
  orchestrator_port: "50051"
  computing_power: 100

data_base: {}

logging:
  to_file: true
  logging_dir: ./logs
  logging_format: json
  logging_file_max_size: 10
  logging_max_filex: 3